### ISSUE TITLE
因为传出来的东西不光你一个人用..  可否把相关配置给分离出来？

### ISSUE THREAD

**Issue by marlonfan** [qq450192529/practise_tieba#2]
可以搞一个配置示例  然后注释掉啊之类的方法~
然后再.gitignore把你自己本身的配置给忽略掉?
否则你如果配置项里面有数据库账号密码之类的不是所有人都可以看见？

**Comment by marlonfan** [comment]
比如你的conn.php是连接数据库的.  
那么是否可以在同目录创建一个conn.php.back  里面放demo代码
然后在你的README.md文件中说明让别人拉下来以后记得更改.
然后把你本身的conn.php忽略提交呢.

**Comment by marlonfan** [comment]
我看到你的根目录下config.yaml文件也是SAE独有的.  那么你是否也可以把它给忽略掉.

**Comment by qq450192529** [comment]
百度到以下情况：
gitignore文件需要注意：
如果某个文件已经在git的版本控制中了，那么即使添加到.gitignore文件中也是没有用的
如果要屏蔽整个文件夹target，在.gitignore中的写法是target/,记得斜杠是写在后面的，而不是/target

那么，此种情况是否要删除掉本地的文件，push一次，然后添加好文件后再次push一次，进行测试

**Comment by qq450192529** [comment]
测试成功

**Comment by qq450192529** [comment]
测试成功

**Comment by qq450192529** [comment]
测试成功
1，删除掉已经上传但不想提交的文件
     提交后，成功删除掉
2，将先前不想提交的文件再次添加到本地版本库中
    SourceTree不会检测这些更改，当然在提交的时候也就不会提交
