### ISSUE TITLE
冗余文件

### ISSUE THREAD

**Issue by marlonfan** [qq450192529/practise_tieba#3]
我看到你这是一个贴吧项目,但是为什么里面有个子目录名字也叫贴吧？你为什么要把你的统计项目放进来？是否可以分离？

**Comment by qq450192529** [comment]
后期的想法是做成博客效果，准备进行修改，按照导航栏做不同的文件夹，统计项目，贴吧项目分别为文件夹，可以这样子，设计目录吗

**Comment by marlonfan** [comment]
ok...那你把项目名字改掉  不要有歧义~
还有哪个readme.md
这样的话你是否可以考虑把账号密码这些东西抽离出来.  搞成一个配置文件?
然后如果连得数据库如果都是一个,为什么要搞三个conn.php

**Comment by qq450192529** [comment]
昨天晚上就在想这个问题
1，考虑到调取时用根目录会比较方便，但这样也造成了重复的文件一直建立
2,后来想到了下面的方案
调取的路径更改为统一路径
上线测试用http://beibeijie.sinaapp.com/conn.php
本地测试用http://localhost/blog/conn.php
3，但这样会产生以下问题
上线测试与本地测试时要修改三个index.php文件中调用conn.php的路径。
求教有什么好的办法可以进行更方便的调用

**Comment by marlonfan** [comment]
@qq450192529 是否可以在根目录简历一个config.php?  配置项全放在里面? 如果其他地方有用到的情况下只需要include就OK了？

**Comment by qq450192529** [comment]
假设现在在目录/aaa/bbb/ccc下的index.php
需要include根目录下的conn.php
那么写法是下面这样吗
线上用 http://beibeijie.sinaapp.com/conn.php
本地测试用http://localhost/blog/conn.php

我觉得这样的写法肯定不对吧，需要一直改index.php，我混入了这样的逻辑中，求指点

大神，去跑步了，回来查看github，谢了。。

**Comment by marlonfan** [comment]
自行百度 **DIR** 魔术常量 or 之后有个composer的东西可以解决掉这个麻烦...  再或者可以写autoload方法.

**Comment by marlonfan** [comment]
@qq450192529 你解决这个问题了么...

**Comment by qq450192529** [comment]
@MarlonFan 
原问：目录/aaa/bbb/ccc下的index.php需include网站根目录下的conn.php。
因此问题归结于如何获取网站的根目录。

DIR魔术常量是用来获取当前文件的目录，不适用于此例。
查询composer感觉绕到我不太懂的地方了
autoload方法暂未查询。

自行百度到的解决方案
$dir = $_SERVER['DOCUMENT_ROOT'];
//获取到网站的根目录
include($dir.'conn.php');
//成功将根目录下的conn.php加入网站子目录下的文件中。

电脑刚新装系统，暂未更新代码，魔都相聚，共赢2016 /握手

**Comment by marlonfan** [comment]
什么时候的鬼...  你可真行...

**Comment by qq450192529** [comment]
@MarlonFan 
顺丰陆运坑爹啊，昨天固态才到，我这主板有点老，昨晚四点多才彻底安好重装了系统，飞一样的感觉。看到留下个问题，不让让它永远停留哪，就上来解决了。

**Comment by marlonfan** [comment]
早点睡吧，这两天好好休息下
